# Generated by Django 5.2.5 on 2025-08-19 16:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Rooftop terrace', 'Rooftop terrace'), ('Fitness center', 'Fitness center'), ('24/7 concierge', '24/7 concierge'), ('Indoor pool', 'Indoor pool')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Villa', 'Villa'), ('Compound', 'Compound')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InteriorFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Floor-to-ceiling windows', 'Floor-to-ceiling windows'), ('Hardwood flooring', 'Hardwood flooring'), ('Gourmet kitchen', 'Gourmet kitchen'), ('In-unit washer/dryer', 'In-unit washer/dryer')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('main_image', models.FileField(upload_to='MainFile/')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('rent', models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_price', models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('security_deposit', models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('bathrooms', models.PositiveIntegerField()),
                ('bedrooms', models.PositiveIntegerField()),
                ('meter', models.DecimalField(decimal_places=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('available_at', models.DateField(blank=True, null=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('available', models.BooleanField(default=False)),
                ('property_type', models.CharField(choices=[('For Rent', 'For Rent'), ('For Sale', 'For Sale')], max_length=100)),
                ('slug', models.CharField(blank=True, max_length=100, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL)),
                ('building_amenities', models.ManyToManyField(blank=True, to='core.buildingamenities')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('interior_features', models.ManyToManyField(blank=True, to='core.interiorfeatures')),
            ],
            options={
                'verbose_name': 'property',
                'verbose_name_plural': 'properties',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Gallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(blank=True, null=True, upload_to='Properites_Gallary/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallaries', to='core.property')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Scheduling a viewing', 'Scheduling a viewing'), ('Getting more information', 'Getting more information'), ('Submitting an application', 'Submitting an application')], max_length=100)),
                ('message', models.TextField(blank=True, max_length=300)),
                ('schedule_date', models.DateField()),
                ('propertymodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.property')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
