# Generated by Django 5.2.5 on 2025-09-18 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_propertymodel_schedule_properties_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ('-schedule_date',), 'verbose_name': 'Schedule', 'verbose_name_plural': 'Schedules'},
        ),
    ]
